### PR TITLE
TM-1-TEAM-C-Back-Button-on-Language-Selection-Screen

### PR DESCRIPTION
**Pull request by kilicma**
I did backButton on LanguageFragment.

### CODE REVIEW

**Comment by Kaancnkya** [comment]
GREAT!

**Review by oliver-basoglu — CHANGES_REQUESTED** [review]
These 2 requirements are not covered:

- Remove any unused functions or methods from the code in the Language Screen.
- Identify and update any deprecated functions or methods with their recommended replacements.

**Comment by oliver-basoglu** [comment]
@kilicma Orda bazi depreceated olan method var. Onuda duzeltmek gerekiyor. Birde master degil develop-a point 
ediyor olman lazim

**Review by oliver-basoglu — DISMISSED** [review]

**Comment by Kaancnkya** [comment]
Great!

**Comment by cihancelik7** [comment]
Yeey

**Review by cihancelik7 — APPROVED** [review]

**Review by Kaancnkya — APPROVED** [review]

**Pull request merged**
