### PR TITLE
TM-6-TEAM-B-Privacy-Policy add WebUtil

### PR DESCRIPTION
**Pull request by Umitytsr**
I added a WebUtil object and added the process of clicking on the profile fragment.

### CODE REVIEW

**Comment by cihancelik7** [comment]
great!!

**Review by mfemree — COMMENTED** [review]
well done!

**Review by Feyzarkt — COMMENTED** [review]
Please update the branch to be pushed as "developB"

**Review by oliver-basoglu — APPROVED** [review]
Good job :)

**Review by oliver-basoglu — CHANGES_REQUESTED** [review]
You should point to master.

**Comment by Kaancnkya** [comment]
good job

**Review by Kaancnkya — DISMISSED** [review]

**Review by oliver-basoglu — APPROVED** [review]
Good work :)

**Review by ulusalemin56 — APPROVED** [review]

**Pull request merged**
